---
- name: Install Winbind
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - samba
    - winbind
    - libpam-winbind
    - libnss-winbind
    - krb5-config
    - krb5-user

- name: "Update Kerberos configuration"
  template:
    src: "krb5.conf"
    dest: "/etc/krb5.conf"

- name: "Update Samba configuration"
  ini_file:
    path: "/etc/samba/smb.conf"
    section: "global"
    option:  "{{ item.option  }}"
    value:   "{{ item.value   }}"
  with_items: "{{ winbind_samba_conf }}"
  notify:
    - "samba_restart"
    - "winbind_restart"

- name: "Remove Samba Printers"
  ini_file:
    path: "/etc/samba/smb.conf"
    section: "{{ item }}"
    state: "absent"
  with_items:
    - "printers"
    - "print$"
  notify: "samba_restart"

- name: "Update nsswitch.conf"
  lineinfile:
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line   }}"
    dest: "/etc/nsswitch.conf"
  with_items:
    - { regexp: '^passwd:', line: 'passwd:		compat winbind' }
    - { regexp: '^group:' , line: 'group:		compat winbind' }
    - { regexp: '^shadow:', line: 'shadow:		compat winbind' }
  notify: "samba_restart"

- name: "Configure PAM authentication"
  template: "src=common-auth dest=/etc/pam.d/common-auth"
  notify: "samba_restart"

- name: "Configure home directory creation"
  lineinfile:
    dest: "/etc/pam.d/common-session"
    regexp: "pam_mkhomedir"
    line: "session optional        pam_mkhomedir.so skel=/etc/skel/ umask=077"
  notify: "samba_restart"

- name: "Check domain status"
  command: "wbinfo --own-domain"
  register: "domain"

- name: "Join domain"
  command: "net join -U {{ winbind_domain_admin.user }}%{{ winbind_domain_admin.pass }}"
  no_log: True
  when: domain.stdout != winbind_workgroup

- name: "Group mapping"
  include_tasks: "groups.yml"
  vars:
    groupmap: "{{ item }}"
  with_items: "{{ winbind_groupmap_admins | union(winbind_groupmap_users)}}"

- name: "Grant SeDiskOperatorPrivilige to Domain Admins (may have to reboot and try again)"
  command: "net rpc rights grant '{{ winbind_workgroup }}+Domain Admins' SeDiskOperatorPrivilege -U {{ winbind_domain_admin.user }}%{{ winbind_domain_admin.pass }}"
  ignore_errors: True
  
...